{{- if .Values.configMap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "checkout.configMapName" . }}
data:
  RETAIL_CHECKOUT_PERSISTENCE_PROVIDER: {{ .Values.app.persistence.provider }}
  {{- if (eq "redis" .Values.app.persistence.provider) }}
  {{- if .Values.redis.create }}
  RETAIL_CHECKOUT_PERSISTENCE_REDIS_URL: redis://{{ include "checkout.redis.fullname" . }}:{{ .Values.redis.service.port }}
  {{- else }}
  {{- $scheme := ternary "rediss" "redis" .Values.app.persistence.redis.tls }}
  RETAIL_CHECKOUT_PERSISTENCE_REDIS_URL: {{ $scheme }}://{{ .Values.app.persistence.redis.endpoint }}
  {{- end }}
  {{- if .Values.app.endpoints.orders }}
  RETAIL_CHECKOUT_ENDPOINTS_ORDERS: {{ .Values.app.endpoints.orders }}
  {{- end }}
  {{- end }}
{{- end }}
