[tools]
java = "21"
node = "22"
terraform = "1.14"
kubectl = "1.34"
helm = "3.19"
helmfile = "1.2"
awscli = "latest"
jq = "latest"
maven = "3.9"
go = "1.25"

[tools."ubi:kubernetes-sigs/kind"]
version = "0.31"

[tools."ubi:tilt-dev/tilt"]
version = "0.36"

[env]
_.path = ["./node_modules/.bin"]
