management:
  endpoints:
    web:
      exposure:
        include: "*"

spring.autoconfigure.exclude:
  - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  - io.awspring.cloud.autoconfigure.sqs.SqsAutoConfiguration

server:
  port: ${port:8080}

spring.flyway.baseline-on-migrate: true

retail:
  orders:
    messaging:
      provider: "in-memory"
