releases:
- name: "catalog"
  namespace: "default"
  chart: ./catalog
  wait: true
  values:
  - templates/components.yaml.gotmpl
  - templates/catalog.yaml.gotmpl

- name: "carts"
  namespace: "default"
  chart: ./carts
  wait: true
  values:
  - templates/components.yaml.gotmpl
  - templates/carts.yaml.gotmpl

- name: "orders"
  namespace: "default"
  chart: ./orders
  wait: true
  values:
  - templates/components.yaml.gotmpl
  - templates/orders.yaml.gotmpl

- name: "checkout"
  namespace: "default"
  chart: ./checkout
  wait: true
  values:
  - templates/components.yaml.gotmpl
  - templates/checkout.yaml.gotmpl
  - endpoints:
      orders: http://orders:80

- name: "assets"
  namespace: "default"
  chart: ./assets
  wait: true
  values:
  - templates/components.yaml.gotmpl
  - templates/assets.yaml.gotmpl

- name: "ui"
  namespace: "default"
  chart: ./ui
  wait: true
  timeout: 600
  values:
  - templates/components.yaml.gotmpl
  - templates/ui.yaml.gotmpl
  - templates/ingress.yaml.gotmpl
  - endpoints:
      catalog: http://catalog
      carts: http://carts
      checkout: http://checkout
      orders: http://orders
      assets: http://assets