version: '3.4'

services:
  orders:
    build:
      context: .
      dockerfile: ../../images/java17/Dockerfile
      args:
        JAR_PATH: target/orders-0.0.1-SNAPSHOT.jar
    image: microservices-demo/orders
    hostname: orders
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - reschedule=on-node-failure
      - SERVER_TOMCAT_ACCESSLOG_ENABLED=true
      - SPRING_PROFILES_ACTIVE=rabbitmq
      - SPRING_DATASOURCE_URL=jdbc:postgresql://orders-db:5432/orders
      - SPRING_DATASOURCE_USERNAME=orders_user
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - "8083:8080"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:8080/actuator/health || exit 1"
        ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 15s

  # nosemgrep: yaml.docker-compose.security.writable-filesystem-service.writable-filesystem-service
  orders-db:
    image: postgres:16.1
    hostname: orders-db
    restart: always
    security_opt:
      - no-new-privileges:true
    environment:
      - reschedule=on-node-failure
      - POSTGRES_PASSWORD=${MYSQL_PASSWORD}
      - POSTGRES_DB=orders
      - POSTGRES_USER=orders_user
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d orders -U orders_user" ]
      interval: 10s
      timeout: 5s
      retries: 30

  # nosemgrep: yaml.docker-compose.security.writable-filesystem-service.writable-filesystem-service
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - "61616:61616"
      - "8161:8161"
