# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

version: '2'

services:
  ui:
    ports:
    - 8888:8080
    environment:
      - JAVA_OPTS=-XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom
      - SERVER_TOMCAT_ACCESSLOG_ENABLED=true
      - ENDPOINTS_CATALOG=http://catalog:8080
      - ENDPOINTS_CARTS=http://carts:8080
      - ENDPOINTS_ORDERS=http://orders:8080
      - ENDPOINTS_CHECKOUT=http://checkout:8080
      - ENDPOINTS_ASSETS=http://assets:8080
    hostname: ui
    image: public.ecr.aws/aws-containers/retail-store-sample-ui:${TAG}
    restart: always
    mem_limit: 256m
    cap_drop:
      - ALL

  catalog:
    hostname: catalog
    image: public.ecr.aws/aws-containers/retail-store-sample-catalog:${TAG}
    restart: always
    environment:
      - GIN_MODE=release
      - DB_PASSWORD=${MYSQL_PASSWORD}
    mem_limit: 128m
    cap_drop:
      - ALL

  catalog-db:
    image: mariadb:10.9
    hostname: catalog-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=sampledb
      - MYSQL_USER=catalog_user
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    mem_limit: 128m

  carts:
    hostname: carts
    image: public.ecr.aws/aws-containers/retail-store-sample-cart:${TAG}
    restart: always
    environment:
      - JAVA_OPTS=-XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom
      - SERVER_TOMCAT_ACCESSLOG_ENABLED=true
      - SPRING_PROFILES_ACTIVE=dynamodb
      - CARTS_DYNAMODB_ENDPOINT=http://carts-db:8000
      - CARTS_DYNAMODB_CREATETABLE=true
      - AWS_ACCESS_KEY_ID=key
      - AWS_SECRET_ACCESS_KEY=dummy
    mem_limit: 256m
    cap_drop:
      - ALL

  carts-db:
    image: amazon/dynamodb-local:1.20.0
    hostname: carts-db
    restart: always
    mem_limit: 128m
    
  orders:
    hostname: orders
    image: public.ecr.aws/aws-containers/retail-store-sample-orders:${TAG}
    restart: always
    environment:
      - JAVA_OPTS=-XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom
      - SERVER_TOMCAT_ACCESSLOG_ENABLED=true
      - SPRING_PROFILES_ACTIVE=mysql,rabbitmq
      - SPRING_DATASOURCE_WRITER_URL=jdbc:mariadb://orders-db:3306/orders
      - SPRING_DATASOURCE_WRITER_USERNAME=orders_user
      - SPRING_DATASOURCE_WRITER_PASSWORD=${MYSQL_PASSWORD}
      - SPRING_DATASOURCE_READER_URL=jdbc:mariadb://orders-db:3306/orders
      - SPRING_DATASOURCE_READER_USERNAME=orders_user
      - SPRING_DATASOURCE_READER_PASSWORD=${MYSQL_PASSWORD}
      - SPRING_RABBITMQ_HOST=rabbitmq
    mem_limit: 256m
    cap_drop:
      - ALL

  orders-db:
    image: mariadb:10.9
    hostname: orders-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=orders
      - MYSQL_USER=orders_user
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    mem_limit: 128m

  checkout:
    image: public.ecr.aws/aws-containers/retail-store-sample-checkout:${TAG}
    hostname: checkout
    restart: always
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - REDIS_URL=redis://checkout-redis:6379
      - ENDPOINTS_ORDERS=http://orders:8080
    mem_limit: 256m
    cap_drop:
      - ALL

  checkout-redis:
    image: redis:6-alpine
    hostname: checkout-redis
    restart: always
    mem_limit: 128m

  assets:
    hostname: assets
    environment:
      - PORT=8080
    image: public.ecr.aws/aws-containers/retail-store-sample-assets:${TAG}
    restart: always
    mem_limit: 64m
    cap_drop:
      - ALL

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"