name: OSS

on:
  workflow_dispatch:

jobs:
  attribution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Install
        run: |
          git clone https://github.com/oss-review-toolkit/ort.git /tmp/ort
          (cd /tmp/ort && git checkout 7b210df2e29f32586a51d2ca8984b17d155e79b3 && ./gradlew installDist)
          echo "/tmp/ort/cli/build/install/ort/bin" >> $GITHUB_PATH

          go install github.com/google/go-licenses@v1.5.0
          
          (cd oss/attribution && pip3 install -r requirements.txt)

      - name: Run
        run: |
          bash oss/run.sh
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          add-path: src/**/ATTRIBUTION.md
          branch: attribution-updates
          title: "chore(deps): Update OSS attribution"
          commit-message: "[Automated] Updating OSS attribution documents"
          delete-branch: true
